// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Cfgrammar = require("../src/cfgrammar.bs.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");

var prod_rules = Caml_array.caml_make_vect(1, Cfgrammar.rule("A", [
          Cfgrammar.Types.t("a"),
          Cfgrammar.Types.nt("B")
        ]));

var start = "S";

var gram = Cfgrammar.Types.grammar(prod_rules, start);

console.log(gram);

exports.prod_rules = prod_rules;
exports.start = start;
exports.gram = gram;
/* prod_rules Not a pure module */
