// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Cfgrammar = require("../src/cfgrammar.bs.js");
var CfgrammarTool = require("./../node_modules/cfgrammar-tool");

var cfgrammar_js = CfgrammarTool;

console.log(Cfgrammar.equals(Cfgrammar.Types.sym("NT", "A"), (new cfgrammar_js.types.Sym("NT","A"))));

var obj = Cfgrammar.Types.sym("NT", "A");

console.log((typeof obj));

Jest.test("Returns Symbol Object", (function (param) {
        return Jest.Expect.toBe(true, Jest.Expect.expect(Cfgrammar.equals(Cfgrammar.Types.sym("NT", "A"), (new cfgrammar_js.types.Sym("NT","A")))));
      }));

exports.cfgrammar_js = cfgrammar_js;
exports.obj = obj;
/* cfgrammar_js Not a pure module */
