
name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        always-auth: false 
        node-version: 13.x 
    - name: Install Dependencies
      run: npm install
    - name: Run Build (Compile ReasonML files)
      run: npm run build
    - name: Run Tests
      run: npm test
